In [1]:
from keras.utils import np_utils
import numpy as np

Using TensorFlow backend.


## One hot encode

In [2]:
texto = "Bom dia! Hoje é quarta feira"
texto = texto.lower()

In [3]:
# create mapping of unique chars to integers
chars = sorted(list(set(texto)))
char_to_int = dict((c, i) for i, c in enumerate(chars))

In [4]:
print(chars)

[' ', '!', 'a', 'b', 'd', 'e', 'f', 'h', 'i', 'j', 'm', 'o', 'q', 'r', 't', 'u', 'é']


In [5]:
print(char_to_int)

{'é': 16, 'm': 10, 'o': 11, ' ': 0, '!': 1, 'r': 13, 'u': 15, 'j': 9, 'd': 4, 'i': 8, 't': 14, 'q': 12, 'f': 6, 'e': 5, 'a': 2, 'b': 3, 'h': 7}


In [6]:
dataY = []

In [7]:
dataY.append([char_to_int[char] for char in texto])

In [8]:
print(dataY)

[[3, 11, 10, 0, 4, 8, 2, 1, 0, 7, 11, 9, 5, 0, 16, 0, 12, 15, 2, 13, 14, 2, 0, 6, 5, 8, 13, 2]]


In [9]:
# one hot encode the output variable
y = np_utils.to_categorical(dataY)

In [10]:
print(y)

[[ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. 

## Reverse

In [11]:
uniques, ids = np.unique(dataY, return_inverse=True)

In [12]:
print(uniques)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [13]:
print(ids)

[ 3 11 10  0  4  8  2  1  0  7 11  9  5  0 16  0 12 15  2 13 14  2  0  6  5
  8 13  2]


In [14]:
int_to_char = dict((i, c) for i, c in enumerate(chars))

In [15]:
print(int_to_char)

{0: ' ', 1: '!', 2: 'a', 3: 'b', 4: 'd', 5: 'e', 6: 'f', 7: 'h', 8: 'i', 9: 'j', 10: 'm', 11: 'o', 12: 'q', 13: 'r', 14: 't', 15: 'u', 16: 'é'}


In [16]:
''.join([int_to_char[value] for value in ids])

'bom dia! hoje é quarta feira'